{% set name = "coiled-runtime" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - python >=3.8,<3.11
    - pip
    - coiled >=0.2.41
    - numpy ==1.21.6
    - pandas ==1.4.2
    - dask ==2022.6.0
    - distributed ==2022.6.0
    - fsspec ==2022.5.0
    - s3fs ==2022.5.0
    - gcsfs ==2022.5.0
    - pyarrow ==8.0.0
    - jupyterlab ==3.4.2
    - dask-labextension ==5.2.0
    - lz4 ==4.0.0
    - ipywidgets ==7.7.0
    - numba ==0.55.1
    - scikit-learn ==1.1.1
    - ipycytoscape ==1.3.3
    - click ==8.1.3
    - xarray ==2022.3.0
    - zarr ==2.11.3
    - msgpack-python ==1.0.3
    - cloudpickle ==2.1.0
    - tornado ==6.1
    - toolz ==0.11.2
    - python-blosc ==1.10.2
    - zict ==2.2.0
    - xgboost ==1.6.1
    - dask-ml ==2022.5.27
    - openssl >1.1.0g
    - bokeh ==2.4.3

test:
  imports:
    - dask
    - distributed
    - pyarrow

about:
  home: https://github.com/coiled/coiled-runtime
  summary:  "Simple and fast way to get started with Dask"
  description: |
    Coiled Runtime is a metapackage that pins Dask, and 
    other packages commonly used with Dask, to a specific 
    version combination that has been verified 
    to work under common use cases / stress testing.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hayesgb
    - ncclementi
    - jrbourbeau
