{% set name = "coiled-runtime" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  noarch: generic

requirements:
  run:
    - python >=3.8,<3.11
    - pip
    - coiled >=0.2.41
    - numpy ==1.23.5
    - pandas ==1.5.2
    - dask ==2022.11.1
    - distributed ==2022.11.1
    - fsspec ==2022.11.0
    - s3fs ==2022.11.0
    - gcsfs ==2022.11.0
    - pyarrow ==10.0.1
    - jupyterlab ==3.5.0
    - dask-labextension ==6.0.0
    - lz4 ==4.0.2
    - ipywidgets ==7.7.2
    - numba ==0.56.3
    - scikit-learn ==1.1.3
    - ipycytoscape ==1.3.3
    - click ==8.1.3
    - xarray ==2022.11.0
    - zarr ==2.13.3
    - msgpack-python ==1.0.4
    - cloudpickle ==2.2.0
    - tornado ==6.1
    - toolz ==0.12.0
    - zict ==2.2.0
    - xgboost ==1.7.1
    - dask-ml ==2022.5.27
    - openssl >1.1.0g
    - pynvml ==11.4.1
    - bokeh ==2.4.3

test:
  imports:
    - dask
    - distributed
    - pyarrow

about:
  home: https://github.com/coiled/coiled-runtime
  summary:  "Simple and fast way to get started with Dask"
  description: |
    Coiled Runtime is a metapackage that pins Dask, and 
    other packages commonly used with Dask, to a specific 
    version combination that has been verified 
    to work under common use cases / stress testing.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hayesgb
    - ncclementi
    - jrbourbeau
